/**
 * Auto-gera configurações de IA baseado no template/subnicho selecionado
 * Isso permite que o usuário não precise configurar manualmente a personalidade, instruções, etc.
 */

import { SubnichoType, NichoType, TomVoz, FluxoAtendimento } from '../types';

interface AutoGeneratedConfig {
  aiIdentity: string;
  aiObjective: string;
  aiInstructions: string;
  aiRestrictions: string;
  toneOfVoice: TomVoz;
  fluxoAtendimento: FluxoAtendimento;
}

// Mapeamento de subnicho para nome amigável
const SUBNICHO_NAMES: Record<SubnichoType, string> = {
  // Saúde
  clinica_medica: 'clínica médica',
  hospital: 'hospital',
  dentista: 'consultório odontológico',
  fisioterapia: 'clínica de fisioterapia',
  psicologia: 'consultório de psicologia',
  nutricao: 'consultório de nutrição',
  laboratorio: 'laboratório de análises',
  farmacia: 'farmácia',
  // Estética
  transplante_capilar: 'clínica de transplante capilar',
  clinica_estetica: 'clínica de estética',
  salao_beleza: 'salão de beleza',
  barbearia: 'barbearia',
  spa: 'spa',
  micropigmentacao: 'estúdio de micropigmentação',
  depilacao: 'clínica de depilação',
  // Vendas
  produtos_hospitalares: 'loja de produtos hospitalares',
  celulares_eletronicos: 'loja de eletrônicos',
  roupas_moda: 'loja de roupas',
  joias_acessorios: 'joalheria',
  cosmeticos: 'loja de cosméticos',
  suplementos: 'loja de suplementos',
  moveis_decoracao: 'loja de móveis',
  // Imobiliário
  agente_imobiliario: 'corretor de imóveis',
  imobiliaria: 'imobiliária',
  construtora: 'construtora',
  administradora: 'administradora de condomínios',
  // Alimentação
  restaurante: 'restaurante',
  delivery: 'delivery',
  lanchonete: 'lanchonete',
  pizzaria: 'pizzaria',
  cafeteria: 'cafeteria',
  confeitaria: 'confeitaria',
  food_truck: 'food truck',
  // Serviços
  advocacia: 'escritório de advocacia',
  contabilidade: 'escritório de contabilidade',
  consultoria: 'consultoria',
  academia_personal: 'academia',
  oficina_mecanica: 'oficina mecânica',
  pet_shop_veterinario: 'pet shop',
  limpeza_manutencao: 'empresa de limpeza',
  marketing_agencia: 'agência de marketing',
  cursos_educacao: 'escola',
  eventos: 'empresa de eventos',
  fotografia: 'estúdio de fotografia',
  tecnologia_ti: 'empresa de tecnologia',
  // Outros
  personalizado: 'empresa',
};

// Termos específicos por nicho
const TERMOS_CLIENTE: Record<NichoType, string> = {
  saude: 'pacientes',
  estetica: 'clientes',
  vendas: 'clientes',
  imobiliario: 'clientes',
  alimentacao: 'clientes',
  servicos: 'clientes',
  outros: 'clientes',
};

const ACAO_PRINCIPAL: Record<NichoType, string> = {
  saude: 'agendar consultas e esclarecer dúvidas sobre procedimentos',
  estetica: 'agendar procedimentos e apresentar tratamentos disponíveis',
  vendas: 'apresentar produtos, tirar dúvidas e direcionar para compra',
  imobiliario: 'apresentar imóveis, agendar visitas e qualificar leads',
  alimentacao: 'apresentar cardápio, tirar pedidos e informar sobre funcionamento',
  servicos: 'agendar atendimentos, esclarecer dúvidas e captar novos clientes',
  outros: 'atender clientes, tirar dúvidas e direcionar para o serviço adequado',
};

export function autoGenerateConfig(
  nicho: NichoType | null,
  subnicho: SubnichoType | null,
  attendantName: string,
  companyName: string,
  professionalName: string
): AutoGeneratedConfig {
  const nichoFinal = nicho || 'outros';
  const subnichoFinal = subnicho || 'personalizado';
  
  const nomeNegocio = SUBNICHO_NAMES[subnichoFinal] || 'empresa';
  const termoCliente = TERMOS_CLIENTE[nichoFinal];
  const acaoPrincipal = ACAO_PRINCIPAL[nichoFinal];

  // Identidade gerada automaticamente
  const aiIdentity = `Sou ${attendantName}, assistente virtual ${
    companyName ? `da ${companyName}` : `de ${nomeNegocio}`
  }. Meu papel é atender nossos ${termoCliente} com simpatia e eficiência, ${acaoPrincipal}.`;

  // Objetivo gerado automaticamente
  const aiObjective = `Meu principal objetivo é oferecer um atendimento humanizado e eficiente, ajudando ${termoCliente} a ${
    nichoFinal === 'saude' ? 'agendar consultas e obter informações sobre nossos serviços médicos' :
    nichoFinal === 'estetica' ? 'conhecer nossos tratamentos e agendar procedimentos' :
    nichoFinal === 'vendas' ? 'encontrar os produtos ideais e realizar compras' :
    nichoFinal === 'imobiliario' ? 'encontrar o imóvel ideal e agendar visitas' :
    nichoFinal === 'alimentacao' ? 'conhecer nosso cardápio e fazer pedidos' :
    'resolver suas necessidades da melhor forma possível'
  }. Quero que cada pessoa se sinta bem atendida e volte a nos procurar.`;

  // Instruções geradas automaticamente
  const aiInstructions = `
- Seja sempre educado(a), simpático(a) e profissional
- Responda de forma clara e objetiva
- Use emojis com moderação para tornar a conversa mais amigável
- Sempre confirme as informações importantes antes de finalizar
- Se não souber algo, diga que vai verificar e retornará
- Evite respostas muito longas - seja direto ao ponto
- Pergunte o nome do cliente no início da conversa
- ${nichoFinal === 'saude' ? 'Nunca dê diagnósticos ou recomendações médicas' : 'Não prometa o que não pode cumprir'}
- Quando o cliente demonstrar interesse, direcione para o agendamento ou próximo passo
`.trim();

  // Restrições geradas automaticamente
  const aiRestrictions = `
- NUNCA invente informações sobre preços, disponibilidade ou procedimentos
- NUNCA faça promessas que a empresa não possa cumprir
- NUNCA compartilhe dados de outros clientes
- NUNCA discuta política, religião ou temas polêmicos
- ${nichoFinal === 'saude' ? 'NUNCA dê diagnósticos ou prescreva medicamentos' : 'NUNCA fale mal da concorrência'}
- Se não souber responder, transfira para um atendente humano
`.trim();

  // Tom de voz baseado no nicho
  const toneOfVoice: TomVoz = 
    nichoFinal === 'saude' ? 'cordial' :
    nichoFinal === 'estetica' ? 'cordial' :
    nichoFinal === 'alimentacao' ? 'casual' :
    nichoFinal === 'servicos' && subnichoFinal === 'advocacia' ? 'formal' :
    nichoFinal === 'servicos' && subnichoFinal === 'contabilidade' ? 'formal' :
    'cordial';

  // Fluxo de atendimento simplificado e universal
  const fluxoAtendimento: FluxoAtendimento = {
    passosCronologicos: [
      {
        id: 'saudacao',
        ordem: 1,
        titulo: 'Saudação Inicial',
        descricao: `Cumprimentar o cliente, se apresentar como ${attendantName} e perguntar como pode ajudar`,
      },
      {
        id: 'identificacao',
        ordem: 2,
        titulo: 'Identificar Necessidade',
        descricao: 'Entender o que o cliente precisa e qual serviço ele busca',
      },
      {
        id: 'informacoes',
        ordem: 3,
        titulo: 'Fornecer Informações',
        descricao: 'Apresentar os serviços disponíveis e tirar dúvidas',
      },
      {
        id: 'agendamento',
        ordem: 4,
        titulo: 'Direcionar para Ação',
        descricao: nichoFinal === 'vendas' 
          ? 'Direcionar para compra ou enviar mais informações'
          : 'Oferecer agendamento ou próximo passo concreto',
      },
      {
        id: 'confirmacao',
        ordem: 5,
        titulo: 'Confirmar e Finalizar',
        descricao: 'Confirmar informações, agradecer e se despedir',
      },
    ],
    passosExtras: [
      {
        id: 'transferencia',
        ordem: 99,
        titulo: 'Transferir para Humano',
        descricao: 'Quando não conseguir resolver ou cliente solicitar, transferir para atendente humano',
      },
    ],
  };

  return {
    aiIdentity,
    aiObjective,
    aiInstructions,
    aiRestrictions,
    toneOfVoice,
    fluxoAtendimento,
  };
}
