-- Add AI enabled flag to crm_conversations
ALTER TABLE public.crm_conversations
ADD COLUMN IF NOT EXISTS ai_enabled boolean NOT NULL DEFAULT true;

-- Add is_ai_generated flag to crm_messages to identify AI responses
ALTER TABLE public.crm_messages
ADD COLUMN IF NOT EXISTS is_ai_generated boolean NOT NULL DEFAULT false;

-- Add comments for documentation
COMMENT ON COLUMN public.crm_conversations.ai_enabled IS 'Whether AI auto-response is enabled for this conversation';
COMMENT ON COLUMN public.crm_messages.is_ai_generated IS 'Whether this message was generated by the AI agent';